openclimatefix/nowcasting_dataloader

nowcasting_dataloader/batch.py

quick fix for gsp data
usual unitests - nothing new

update to gsp fake data

---

nowcasting_dataloader/data_sources/gsp/gsp_model.py
nowcasting_dataloader/data_sources/pv/pv_model.py
tests/test_netcdf_dataset.py
tests/test_position_encoding.py
tests/test_subselect.py

- normalize gsp and pv data
- waiting for https://github.com/openclimatefix/nowcasting_dataset/pull/427/files
Fixes #56 
unittests

normalization for pv and gsp

---

nowcasting_dataloader/datasets.py
nowcasting_dataloader/fake.py
nowcasting_dataloader/utils/position_encoding.py
tests/test_batch.py
tests/test_position_encoding.py

Updates the FakeDataset with optional position encodings
Fixes #
Unit tests

Update FakeDataset with position encodings

---

nowcasting_dataloader/datamodules.py
tests/test_datamodules.py

Adds in a datamodule for the SatFlowDataset
Fixes #
Unit test

Add SatFlowDataModule

---

nowcasting_dataloader/utils/position_encoding.py

Speed up the position encoding creation
Fixes #75 
Banchmarking and unit tests

Speed up Position Encoding

---

nowcasting_dataloader/data_sources/topographic/topographic_model.py

update topo norm stats

---

nowcasting_dataloader/datasets.py
tests/test_satflow_dataset.py

This PR does a few things
Fixes #88 
Unit tests

Minor fixes for SatFlowDataset

---

nowcasting_dataloader/datamodules.py
nowcasting_dataloader/datasets.py

Enable `SatFlowDataset` to be instantiated with `data_sources_names=('pv', )`.

Fix loading when data_sources_names=('pv', )

---

nowcasting_dataloader/datasets.py
nowcasting_dataloader/utils/position_encoding.py
tests/test_position_encoding.py
tests/test_satflow_dataset.py

Also up the lowest frequency to be higher, so we have more high frequency values
Adds configurable number of bands for the Fourier FEatures, more bands means sampling the Fourier representation more often. Also increases the frequency of the lowest Fourier feature to be higher.
Fixes #
Unit tests

Add configurable number of Fourier bands

---

nowcasting_dataloader/datasets.py

This allows us to have the actual times for plotting in the joint model
Fixes #
Unittests

Add returning the datetime index in SatFlowDataset

---

nowcasting_dataloader/datasets.py

Adds GSP capacity too the target for use in visualizing results
Fixes #
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

Add GSP capacity to target in SatFlowDataset

---

.github/workflows/workflows.yaml

add coverage dir

---

tests/data_sources/satellite/test_satellite_model.py
tests/test_netcdf_dataset.py
tests/test_position_encoding.py
tests/test_subselect.py

Update for fake batch
https://github.com/openclimatefix/nowcasting_dataset/pull/531
Fixes #
uniitests

fix for new fake batch

---

nowcasting_dataloader/data_sources/datasource_output.py
nowcasting_dataloader/data_sources/gsp/gsp_model.py
nowcasting_dataloader/data_sources/pv/pv_model.py
nowcasting_dataloader/datasets.py
scripts/find_pv_gsp_max_min.py
tests/data_sources/test_gsp.py
tests/data_sources/test_pv.py

normalize pv and gsp coordinates
need PR - https://github.com/openclimatefix/nowcasting_dataset/pull/538
Fixes #106 
add unittests

normalize pv and gsp coordiantes

---

nowcasting_dataloader/datamodules.py

Use validation dataset 
unittests

use validation

---

nowcasting_dataloader/datasets.py
tests/test_datamodules.py
tests/test_netcdf_dataset.py

add option to load two batches and mix them together
Will need this [PR](https://github.com/openclimatefix/nowcasting_dataset/pull/555) to work
Fixes #109 
normal unittest

load two batches and mix

---

conftest.py
nowcasting_dataloader/data_sources/opticalflow/__init__.py
tests/test_batch.py
tests/test_datamodules.py
tests/test_netcdf_dataset.py
tests/test_position_encoding.py
tests/test_satflow_dataset.py
tests/test_subselect.py

- fix tests, started by increase default pv systems to 2048
- reduce test code by using fixtures
- NO NEW CODE in library
unittets tests

fix tests, set n pv systems to 128

---

nowcasting_dataloader/batch.py
nowcasting_dataloader/data_sources/metadata/metadata_model.py

add id to metadata in batch ml
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

Add id metadata

---

docs/requirements.txt
nowcasting_dataloader/datasets.py
pydoc-markdown.yml
tests/test_netcdf_dataset.py

Saves out the batch from the dataloader to a given path so it can be used to visualize or debug.
Relates to https://github.com/openclimatefix/nowcasting_forecast/issues/59
Unit test

Save first batch to given location for live batches

---

nowcasting_dataloader/datamodules.py
nowcasting_dataloader/datasets.py
tests/test_netcdf_dataset.py

Give optional nwp channels to dataloader
need for https://github.com/openclimatefix/nowcasting_forecast/issues/94
- added to unittests
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

add option to select nwp channels

---

nowcasting_dataloader/data_sources/gsp/gsp_model.py
tests/data_sources/test_gsp.py

Make sure zero capacity doesnt cause nans or infs
Fixes #
Normal CI
added a test, to check behaviour

make sure gsp 0 capacity doesn make infs
